### ISSUE TITLE
Feature request: Value to sound

### ISSUE THREAD

**Issue by Piripe** [dimtpap/obs-scale-to-sound#5]
You could add some new params to change the value of the source or a filter instead of changing scale. It would be much more useful than just changing scale.

By example, with this feature you could link the Opacity parameter of the Color Correction filter with the sound.

**Comment by dimtpap** [comment]
That's exactly what the Audio Move filter in Exeldro's [Move Transition plugin](https://obsproject.com/forum/resources/move-transition.913/) does. You can find it in the filters of audio sources

**Comment by Piripe** [comment]
Oops, I never heard about this, it's ok so.
