### ISSUE TITLE
OSX Installs into Wrong Directory

### ISSUE THREAD

**Issue by jnovack** [dimtpap/obs-scale-to-sound#7]
On OSX 13.4, I need the `scale-to-sound.plugin `directory under `~/Library/Application Support/obs-studio/plugins` (under MY home directory), not `/Library/Application Support/obs-studio/plugins` (NOT the system directory).

From installing the package, I then dropped to a shell and did the following to fix:

```
sudo mv /Library/Application\ Support/obs-studio/plugins/scale-to-sound.plugin ~/Library/Application\ Support/obs-studio/plugins/
```

xml confuses and scares me, otherwise I'd submit a PR.  It might be this line which needs changing to the user's home directory?

https://github.com/dimtpap/obs-scale-to-sound/blob/6feea3e1a391a64bab7420716985fe259d8939ce/cmake/bundle/macos/installer-macos.pkgproj.in#L15

**Comment by dimtpap** [comment]
The packaging is provided by https://github.com/obsproject/obs-plugintemplate, which is the standard way to package plugins for OBS Studio. I'd assume other OBS Studio plugins are installed the same way on macOS, are they not?

**Comment by jnovack** [comment]
This is the only plug-in I have installed, I didn't test anything else.  I'll take it up over there.  Thank you for responding.
